# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = $(CURDIR)

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = $(CURDIR)

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/AlynCoin/CMakeFiles /root/AlynCoin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/AlynCoin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named protobuf_gen

# Build rule for target.
protobuf_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protobuf_gen
.PHONY : protobuf_gen

# fast build rule for target.
protobuf_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/protobuf_gen.dir/build.make src/CMakeFiles/protobuf_gen.dir/build
.PHONY : protobuf_gen/fast

#=============================================================================
# Target rules for targets named winterfell_ffi

# Build rule for target.
winterfell_ffi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 winterfell_ffi
.PHONY : winterfell_ffi

# fast build rule for target.
winterfell_ffi/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/winterfell_ffi.dir/build.make src/CMakeFiles/winterfell_ffi.dir/build
.PHONY : winterfell_ffi/fast

#=============================================================================
# Target rules for targets named falcon

# Build rule for target.
falcon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 falcon
.PHONY : falcon

# fast build rule for target.
falcon/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/falcon.dir/build.make src/CMakeFiles/falcon.dir/build
.PHONY : falcon/fast

#=============================================================================
# Target rules for targets named dilithium

# Build rule for target.
dilithium: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dilithium
.PHONY : dilithium

# fast build rule for target.
dilithium/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/dilithium.dir/build.make src/CMakeFiles/dilithium.dir/build
.PHONY : dilithium/fast

#=============================================================================
# Target rules for targets named alyncoin_lib

# Build rule for target.
alyncoin_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alyncoin_lib
.PHONY : alyncoin_lib

# fast build rule for target.
alyncoin_lib/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/alyncoin_lib.dir/build.make src/CMakeFiles/alyncoin_lib.dir/build
.PHONY : alyncoin_lib/fast

#=============================================================================
# Target rules for targets named alyncoin

# Build rule for target.
alyncoin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alyncoin
.PHONY : alyncoin

# fast build rule for target.
alyncoin/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/alyncoin.dir/build.make src/CMakeFiles/alyncoin.dir/build
.PHONY : alyncoin/fast

#=============================================================================
# Target rules for targets named alyncoin-cli

# Build rule for target.
alyncoin-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alyncoin-cli
.PHONY : alyncoin-cli

# fast build rule for target.
alyncoin-cli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/alyncoin-cli.dir/build.make src/CMakeFiles/alyncoin-cli.dir/build
.PHONY : alyncoin-cli/fast

#=============================================================================
# Target rules for targets named peer_blacklist_cli

# Build rule for target.
peer_blacklist_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 peer_blacklist_cli
.PHONY : peer_blacklist_cli

# fast build rule for target.
peer_blacklist_cli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/peer_blacklist_cli.dir/build.make src/CMakeFiles/peer_blacklist_cli.dir/build
.PHONY : peer_blacklist_cli/fast

#=============================================================================
# Target rules for targets named swapcli

# Build rule for target.
swapcli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swapcli
.PHONY : swapcli

# fast build rule for target.
swapcli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/swapcli.dir/build.make src/CMakeFiles/swapcli.dir/build
.PHONY : swapcli/fast

#=============================================================================
# Target rules for targets named identitycli

# Build rule for target.
identitycli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 identitycli
.PHONY : identitycli

# fast build rule for target.
identitycli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/identitycli.dir/build.make src/CMakeFiles/identitycli.dir/build
.PHONY : identitycli/fast

#=============================================================================
# Target rules for targets named nftcli

# Build rule for target.
nftcli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nftcli
.PHONY : nftcli

# fast build rule for target.
nftcli/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/nftcli.dir/build.make src/CMakeFiles/nftcli.dir/build
.PHONY : nftcli/fast

#=============================================================================
# Target rules for targets named blacklist_test

# Build rule for target.
blacklist_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blacklist_test
.PHONY : blacklist_test

# fast build rule for target.
blacklist_test/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/blacklist_test.dir/build.make src/CMakeFiles/blacklist_test.dir/build
.PHONY : blacklist_test/fast

#=============================================================================
# Target rules for targets named explorer_server

# Build rule for target.
explorer_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 explorer_server
.PHONY : explorer_server

# fast build rule for target.
explorer_server/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/explorer_server.dir/build.make src/CMakeFiles/explorer_server.dir/build
.PHONY : explorer_server/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... protobuf_gen"
	@echo "... winterfell_ffi"
	@echo "... alyncoin"
	@echo "... alyncoin-cli"
	@echo "... alyncoin_lib"
	@echo "... blacklist_test"
	@echo "... dilithium"
	@echo "... explorer_server"
	@echo "... falcon"
	@echo "... identitycli"
	@echo "... nftcli"
	@echo "... peer_blacklist_cli"
	@echo "... swapcli"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

