// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: blockchain_protos.proto
// Protobuf C++ Version: 5.29.3

#include "blockchain_protos.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace alyncoin {

inline constexpr BlockchainProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : blocks_{},
        pending_transactions_{},
        chain_id_{0},
        difficulty_{0},
        block_reward_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BlockchainProto::BlockchainProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BlockchainProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BlockchainProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BlockchainProtoDefaultTypeInternal() {}
  union {
    BlockchainProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BlockchainProtoDefaultTypeInternal _BlockchainProto_default_instance_;
}  // namespace alyncoin
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_blockchain_5fprotos_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_blockchain_5fprotos_2eproto = nullptr;
const ::uint32_t
    TableStruct_blockchain_5fprotos_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _impl_.chain_id_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _impl_.blocks_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _impl_.pending_transactions_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _impl_.difficulty_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::BlockchainProto, _impl_.block_reward_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::alyncoin::BlockchainProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::alyncoin::_BlockchainProto_default_instance_._instance,
};
const char descriptor_table_protodef_blockchain_5fprotos_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027blockchain_protos.proto\022\010alyncoin\032\022blo"
    "ck_protos.proto\032\030transaction_protos.prot"
    "o\"\255\001\n\017BlockchainProto\022\020\n\010chain_id\030\001 \001(\005\022"
    "$\n\006blocks\030\002 \003(\0132\024.alyncoin.BlockProto\0228\n"
    "\024pending_transactions\030\003 \003(\0132\032.alyncoin.T"
    "ransactionProto\022\022\n\ndifficulty\030\004 \001(\005\022\024\n\014b"
    "lock_reward\030\005 \001(\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_blockchain_5fprotos_2eproto_deps[2] =
    {
        &::descriptor_table_block_5fprotos_2eproto,
        &::descriptor_table_transaction_5fprotos_2eproto,
};
static ::absl::once_flag descriptor_table_blockchain_5fprotos_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_blockchain_5fprotos_2eproto = {
    false,
    false,
    265,
    descriptor_table_protodef_blockchain_5fprotos_2eproto,
    "blockchain_protos.proto",
    &descriptor_table_blockchain_5fprotos_2eproto_once,
    descriptor_table_blockchain_5fprotos_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_blockchain_5fprotos_2eproto::offsets,
    file_level_enum_descriptors_blockchain_5fprotos_2eproto,
    file_level_service_descriptors_blockchain_5fprotos_2eproto,
};
namespace alyncoin {
// ===================================================================

class BlockchainProto::_Internal {
 public:
};

void BlockchainProto::clear_blocks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.blocks_.Clear();
}
void BlockchainProto::clear_pending_transactions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pending_transactions_.Clear();
}
BlockchainProto::BlockchainProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:alyncoin.BlockchainProto)
}
inline PROTOBUF_NDEBUG_INLINE BlockchainProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::alyncoin::BlockchainProto& from_msg)
      : blocks_{visibility, arena, from.blocks_},
        pending_transactions_{visibility, arena, from.pending_transactions_},
        _cached_size_{0} {}

BlockchainProto::BlockchainProto(
    ::google::protobuf::Arena* arena,
    const BlockchainProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BlockchainProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chain_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, chain_id_),
           offsetof(Impl_, block_reward_) -
               offsetof(Impl_, chain_id_) +
               sizeof(Impl_::block_reward_));

  // @@protoc_insertion_point(copy_constructor:alyncoin.BlockchainProto)
}
inline PROTOBUF_NDEBUG_INLINE BlockchainProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : blocks_{visibility, arena},
        pending_transactions_{visibility, arena},
        _cached_size_{0} {}

inline void BlockchainProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chain_id_),
           0,
           offsetof(Impl_, block_reward_) -
               offsetof(Impl_, chain_id_) +
               sizeof(Impl_::block_reward_));
}
BlockchainProto::~BlockchainProto() {
  // @@protoc_insertion_point(destructor:alyncoin.BlockchainProto)
  SharedDtor(*this);
}
inline void BlockchainProto::SharedDtor(MessageLite& self) {
  BlockchainProto& this_ = static_cast<BlockchainProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BlockchainProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BlockchainProto(arena);
}
constexpr auto BlockchainProto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.blocks_) +
          decltype(BlockchainProto::_impl_.blocks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.pending_transactions_) +
          decltype(BlockchainProto::_impl_.pending_transactions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BlockchainProto), alignof(BlockchainProto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BlockchainProto::PlacementNew_,
                                 sizeof(BlockchainProto),
                                 alignof(BlockchainProto));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BlockchainProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BlockchainProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BlockchainProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BlockchainProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BlockchainProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BlockchainProto>(), &BlockchainProto::ByteSizeLong,
            &BlockchainProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_._cached_size_),
        false,
    },
    &BlockchainProto::kDescriptorMethods,
    &descriptor_table_blockchain_5fprotos_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BlockchainProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2> BlockchainProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::alyncoin::BlockchainProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 chain_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BlockchainProto, _impl_.chain_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.chain_id_)}},
    // repeated .alyncoin.BlockProto blocks = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.blocks_)}},
    // repeated .alyncoin.TransactionProto pending_transactions = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 1, PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.pending_transactions_)}},
    // int32 difficulty = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BlockchainProto, _impl_.difficulty_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.difficulty_)}},
    // double block_reward = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.block_reward_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 chain_id = 1;
    {PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.chain_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .alyncoin.BlockProto blocks = 2;
    {PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.blocks_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .alyncoin.TransactionProto pending_transactions = 3;
    {PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.pending_transactions_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 difficulty = 4;
    {PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.difficulty_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double block_reward = 5;
    {PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.block_reward_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }}, {{
    {::_pbi::TcParser::GetTable<::alyncoin::BlockProto>()},
    {::_pbi::TcParser::GetTable<::alyncoin::TransactionProto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void BlockchainProto::Clear() {
// @@protoc_insertion_point(message_clear_start:alyncoin.BlockchainProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.blocks_.Clear();
  _impl_.pending_transactions_.Clear();
  ::memset(&_impl_.chain_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.block_reward_) -
      reinterpret_cast<char*>(&_impl_.chain_id_)) + sizeof(_impl_.block_reward_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BlockchainProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BlockchainProto& this_ = static_cast<const BlockchainProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BlockchainProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BlockchainProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:alyncoin.BlockchainProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 chain_id = 1;
          if (this_._internal_chain_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_chain_id(), target);
          }

          // repeated .alyncoin.BlockProto blocks = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_blocks_size());
               i < n; i++) {
            const auto& repfield = this_._internal_blocks().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .alyncoin.TransactionProto pending_transactions = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_pending_transactions_size());
               i < n; i++) {
            const auto& repfield = this_._internal_pending_transactions().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // int32 difficulty = 4;
          if (this_._internal_difficulty() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_difficulty(), target);
          }

          // double block_reward = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_block_reward()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_block_reward(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:alyncoin.BlockchainProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BlockchainProto::ByteSizeLong(const MessageLite& base) {
          const BlockchainProto& this_ = static_cast<const BlockchainProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BlockchainProto::ByteSizeLong() const {
          const BlockchainProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:alyncoin.BlockchainProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .alyncoin.BlockProto blocks = 2;
            {
              total_size += 1UL * this_._internal_blocks_size();
              for (const auto& msg : this_._internal_blocks()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .alyncoin.TransactionProto pending_transactions = 3;
            {
              total_size += 1UL * this_._internal_pending_transactions_size();
              for (const auto& msg : this_._internal_pending_transactions()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // int32 chain_id = 1;
            if (this_._internal_chain_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chain_id());
            }
            // int32 difficulty = 4;
            if (this_._internal_difficulty() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_difficulty());
            }
            // double block_reward = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_block_reward()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BlockchainProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BlockchainProto*>(&to_msg);
  auto& from = static_cast<const BlockchainProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:alyncoin.BlockchainProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_blocks()->MergeFrom(
      from._internal_blocks());
  _this->_internal_mutable_pending_transactions()->MergeFrom(
      from._internal_pending_transactions());
  if (from._internal_chain_id() != 0) {
    _this->_impl_.chain_id_ = from._impl_.chain_id_;
  }
  if (from._internal_difficulty() != 0) {
    _this->_impl_.difficulty_ = from._impl_.difficulty_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_block_reward()) != 0) {
    _this->_impl_.block_reward_ = from._impl_.block_reward_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BlockchainProto::CopyFrom(const BlockchainProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alyncoin.BlockchainProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BlockchainProto::InternalSwap(BlockchainProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.blocks_.InternalSwap(&other->_impl_.blocks_);
  _impl_.pending_transactions_.InternalSwap(&other->_impl_.pending_transactions_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.block_reward_)
      + sizeof(BlockchainProto::_impl_.block_reward_)
      - PROTOBUF_FIELD_OFFSET(BlockchainProto, _impl_.chain_id_)>(
          reinterpret_cast<char*>(&_impl_.chain_id_),
          reinterpret_cast<char*>(&other->_impl_.chain_id_));
}

::google::protobuf::Metadata BlockchainProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace alyncoin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_blockchain_5fprotos_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
