// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main_protos.proto
// Protobuf C++ Version: 5.29.3

#ifndef main_5fprotos_2eproto_2epb_2eh
#define main_5fprotos_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "block_protos.pb.h"
#include "transaction_protos.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_main_5fprotos_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_main_5fprotos_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_main_5fprotos_2eproto;
namespace alyncoin {
class MainProto;
struct MainProtoDefaultTypeInternal;
extern MainProtoDefaultTypeInternal _MainProto_default_instance_;
}  // namespace alyncoin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace alyncoin {

// ===================================================================


// -------------------------------------------------------------------

class MainProto final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:alyncoin.MainProto) */ {
 public:
  inline MainProto() : MainProto(nullptr) {}
  ~MainProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MainProto* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MainProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MainProto(
      ::google::protobuf::internal::ConstantInitialized);

  inline MainProto(const MainProto& from) : MainProto(nullptr, from) {}
  inline MainProto(MainProto&& from) noexcept
      : MainProto(nullptr, std::move(from)) {}
  inline MainProto& operator=(const MainProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MainProto& operator=(MainProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MainProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const MainProto* internal_default_instance() {
    return reinterpret_cast<const MainProto*>(
        &_MainProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MainProto& a, MainProto& b) { a.Swap(&b); }
  inline void Swap(MainProto* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MainProto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MainProto* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MainProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MainProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MainProto& from) { MainProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MainProto* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "alyncoin.MainProto"; }

 protected:
  explicit MainProto(::google::protobuf::Arena* arena);
  MainProto(::google::protobuf::Arena* arena, const MainProto& from);
  MainProto(::google::protobuf::Arena* arena, MainProto&& from) noexcept
      : MainProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBlocksFieldNumber = 1,
    kTransactionsFieldNumber = 2,
  };
  // repeated .alyncoin.BlockProto blocks = 1;
  int blocks_size() const;
  private:
  int _internal_blocks_size() const;

  public:
  void clear_blocks() ;
  ::alyncoin::BlockProto* mutable_blocks(int index);
  ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>* mutable_blocks();

  private:
  const ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>& _internal_blocks() const;
  ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>* _internal_mutable_blocks();
  public:
  const ::alyncoin::BlockProto& blocks(int index) const;
  ::alyncoin::BlockProto* add_blocks();
  const ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>& blocks() const;
  // repeated .alyncoin.TransactionProto transactions = 2;
  int transactions_size() const;
  private:
  int _internal_transactions_size() const;

  public:
  void clear_transactions() ;
  ::alyncoin::TransactionProto* mutable_transactions(int index);
  ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>* mutable_transactions();

  private:
  const ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>& _internal_transactions() const;
  ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>* _internal_mutable_transactions();
  public:
  const ::alyncoin::TransactionProto& transactions(int index) const;
  ::alyncoin::TransactionProto* add_transactions();
  const ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>& transactions() const;
  // @@protoc_insertion_point(class_scope:alyncoin.MainProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MainProto& from_msg);
    ::google::protobuf::RepeatedPtrField< ::alyncoin::BlockProto > blocks_;
    ::google::protobuf::RepeatedPtrField< ::alyncoin::TransactionProto > transactions_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_main_5fprotos_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MainProto

// repeated .alyncoin.BlockProto blocks = 1;
inline int MainProto::_internal_blocks_size() const {
  return _internal_blocks().size();
}
inline int MainProto::blocks_size() const {
  return _internal_blocks_size();
}
inline ::alyncoin::BlockProto* MainProto::mutable_blocks(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:alyncoin.MainProto.blocks)
  return _internal_mutable_blocks()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>* MainProto::mutable_blocks()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:alyncoin.MainProto.blocks)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_blocks();
}
inline const ::alyncoin::BlockProto& MainProto::blocks(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:alyncoin.MainProto.blocks)
  return _internal_blocks().Get(index);
}
inline ::alyncoin::BlockProto* MainProto::add_blocks() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::alyncoin::BlockProto* _add = _internal_mutable_blocks()->Add();
  // @@protoc_insertion_point(field_add:alyncoin.MainProto.blocks)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>& MainProto::blocks() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:alyncoin.MainProto.blocks)
  return _internal_blocks();
}
inline const ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>&
MainProto::_internal_blocks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.blocks_;
}
inline ::google::protobuf::RepeatedPtrField<::alyncoin::BlockProto>*
MainProto::_internal_mutable_blocks() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.blocks_;
}

// repeated .alyncoin.TransactionProto transactions = 2;
inline int MainProto::_internal_transactions_size() const {
  return _internal_transactions().size();
}
inline int MainProto::transactions_size() const {
  return _internal_transactions_size();
}
inline ::alyncoin::TransactionProto* MainProto::mutable_transactions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:alyncoin.MainProto.transactions)
  return _internal_mutable_transactions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>* MainProto::mutable_transactions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:alyncoin.MainProto.transactions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_transactions();
}
inline const ::alyncoin::TransactionProto& MainProto::transactions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:alyncoin.MainProto.transactions)
  return _internal_transactions().Get(index);
}
inline ::alyncoin::TransactionProto* MainProto::add_transactions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::alyncoin::TransactionProto* _add = _internal_mutable_transactions()->Add();
  // @@protoc_insertion_point(field_add:alyncoin.MainProto.transactions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>& MainProto::transactions() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:alyncoin.MainProto.transactions)
  return _internal_transactions();
}
inline const ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>&
MainProto::_internal_transactions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transactions_;
}
inline ::google::protobuf::RepeatedPtrField<::alyncoin::TransactionProto>*
MainProto::_internal_mutable_transactions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.transactions_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace alyncoin


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // main_5fprotos_2eproto_2epb_2eh
