// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transaction_protos.proto
// Protobuf C++ Version: 5.29.3

#include "transaction_protos.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace alyncoin {

inline constexpr TransactionProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sender_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        recipient_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        signature_dilithium_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        signature_falcon_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        zkproof_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_pubkey_dilithium_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_pubkey_falcon_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        metadata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        amount_str_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        amount_{0},
        timestamp_{::uint64_t{0u}},
        is_system_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TransactionProto::TransactionProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TransactionProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransactionProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransactionProtoDefaultTypeInternal() {}
  union {
    TransactionProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransactionProtoDefaultTypeInternal _TransactionProto_default_instance_;
}  // namespace alyncoin
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_transaction_5fprotos_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_transaction_5fprotos_2eproto = nullptr;
const ::uint32_t
    TableStruct_transaction_5fprotos_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.sender_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.recipient_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.amount_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.signature_dilithium_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.signature_falcon_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.zkproof_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.sender_pubkey_dilithium_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.sender_pubkey_falcon_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.hash_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.is_system_),
        PROTOBUF_FIELD_OFFSET(::alyncoin::TransactionProto, _impl_.amount_str_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::alyncoin::TransactionProto)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::alyncoin::_TransactionProto_default_instance_._instance,
};
const char descriptor_table_protodef_transaction_5fprotos_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030transaction_protos.proto\022\010alyncoin\"\246\002\n"
    "\020TransactionProto\022\016\n\006sender\030\001 \001(\t\022\021\n\trec"
    "ipient\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001\022\021\n\ttimestam"
    "p\030\004 \001(\004\022\033\n\023signature_dilithium\030\005 \001(\014\022\030\n\020"
    "signature_falcon\030\006 \001(\014\022\017\n\007zkproof\030\007 \001(\014\022"
    "\037\n\027sender_pubkey_dilithium\030\010 \001(\014\022\034\n\024send"
    "er_pubkey_falcon\030\t \001(\014\022\020\n\010metadata\030\n \001(\t"
    "\022\014\n\004hash\030\013 \001(\t\022\021\n\tis_system\030\014 \001(\010\022\022\n\namo"
    "unt_str\030\r \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_transaction_5fprotos_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_transaction_5fprotos_2eproto = {
    false,
    false,
    341,
    descriptor_table_protodef_transaction_5fprotos_2eproto,
    "transaction_protos.proto",
    &descriptor_table_transaction_5fprotos_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_transaction_5fprotos_2eproto::offsets,
    file_level_enum_descriptors_transaction_5fprotos_2eproto,
    file_level_service_descriptors_transaction_5fprotos_2eproto,
};
namespace alyncoin {
// ===================================================================

class TransactionProto::_Internal {
 public:
};

TransactionProto::TransactionProto(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:alyncoin.TransactionProto)
}
inline PROTOBUF_NDEBUG_INLINE TransactionProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::alyncoin::TransactionProto& from_msg)
      : sender_(arena, from.sender_),
        recipient_(arena, from.recipient_),
        signature_dilithium_(arena, from.signature_dilithium_),
        signature_falcon_(arena, from.signature_falcon_),
        zkproof_(arena, from.zkproof_),
        sender_pubkey_dilithium_(arena, from.sender_pubkey_dilithium_),
        sender_pubkey_falcon_(arena, from.sender_pubkey_falcon_),
        metadata_(arena, from.metadata_),
        hash_(arena, from.hash_),
        amount_str_(arena, from.amount_str_),
        _cached_size_{0} {}

TransactionProto::TransactionProto(
    ::google::protobuf::Arena* arena,
    const TransactionProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TransactionProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, amount_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, amount_),
           offsetof(Impl_, is_system_) -
               offsetof(Impl_, amount_) +
               sizeof(Impl_::is_system_));

  // @@protoc_insertion_point(copy_constructor:alyncoin.TransactionProto)
}
inline PROTOBUF_NDEBUG_INLINE TransactionProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : sender_(arena),
        recipient_(arena),
        signature_dilithium_(arena),
        signature_falcon_(arena),
        zkproof_(arena),
        sender_pubkey_dilithium_(arena),
        sender_pubkey_falcon_(arena),
        metadata_(arena),
        hash_(arena),
        amount_str_(arena),
        _cached_size_{0} {}

inline void TransactionProto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, amount_),
           0,
           offsetof(Impl_, is_system_) -
               offsetof(Impl_, amount_) +
               sizeof(Impl_::is_system_));
}
TransactionProto::~TransactionProto() {
  // @@protoc_insertion_point(destructor:alyncoin.TransactionProto)
  SharedDtor(*this);
}
inline void TransactionProto::SharedDtor(MessageLite& self) {
  TransactionProto& this_ = static_cast<TransactionProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sender_.Destroy();
  this_._impl_.recipient_.Destroy();
  this_._impl_.signature_dilithium_.Destroy();
  this_._impl_.signature_falcon_.Destroy();
  this_._impl_.zkproof_.Destroy();
  this_._impl_.sender_pubkey_dilithium_.Destroy();
  this_._impl_.sender_pubkey_falcon_.Destroy();
  this_._impl_.metadata_.Destroy();
  this_._impl_.hash_.Destroy();
  this_._impl_.amount_str_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TransactionProto::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TransactionProto(arena);
}
constexpr auto TransactionProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TransactionProto),
                                            alignof(TransactionProto));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TransactionProto::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TransactionProto_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TransactionProto::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TransactionProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TransactionProto::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TransactionProto>(), &TransactionProto::ByteSizeLong,
            &TransactionProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_._cached_size_),
        false,
    },
    &TransactionProto::kDescriptorMethods,
    &descriptor_table_transaction_5fprotos_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TransactionProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 0, 79, 2> TransactionProto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::alyncoin::TransactionProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string sender = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_)}},
    // string recipient = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.recipient_)}},
    // double amount = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.amount_)}},
    // uint64 timestamp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TransactionProto, _impl_.timestamp_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.timestamp_)}},
    // bytes signature_dilithium = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.signature_dilithium_)}},
    // bytes signature_falcon = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.signature_falcon_)}},
    // bytes zkproof = 7;
    {::_pbi::TcParser::FastBS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.zkproof_)}},
    // bytes sender_pubkey_dilithium = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_pubkey_dilithium_)}},
    // bytes sender_pubkey_falcon = 9;
    {::_pbi::TcParser::FastBS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_pubkey_falcon_)}},
    // string metadata = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.metadata_)}},
    // string hash = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.hash_)}},
    // bool is_system = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TransactionProto, _impl_.is_system_), 63>(),
     {96, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.is_system_)}},
    // string amount_str = 13;
    {::_pbi::TcParser::FastUS1,
     {106, 63, 0, PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.amount_str_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string sender = 1;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string recipient = 2;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.recipient_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double amount = 3;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // uint64 timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bytes signature_dilithium = 5;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.signature_dilithium_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes signature_falcon = 6;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.signature_falcon_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes zkproof = 7;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.zkproof_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes sender_pubkey_dilithium = 8;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_pubkey_dilithium_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes sender_pubkey_falcon = 9;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.sender_pubkey_falcon_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string metadata = 10;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.metadata_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string hash = 11;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_system = 12;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.is_system_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string amount_str = 13;
    {PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.amount_str_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\6\11\0\0\0\0\0\0\0\10\4\0\12\0\0"
    "alyncoin.TransactionProto"
    "sender"
    "recipient"
    "metadata"
    "hash"
    "amount_str"
  }},
};

PROTOBUF_NOINLINE void TransactionProto::Clear() {
// @@protoc_insertion_point(message_clear_start:alyncoin.TransactionProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sender_.ClearToEmpty();
  _impl_.recipient_.ClearToEmpty();
  _impl_.signature_dilithium_.ClearToEmpty();
  _impl_.signature_falcon_.ClearToEmpty();
  _impl_.zkproof_.ClearToEmpty();
  _impl_.sender_pubkey_dilithium_.ClearToEmpty();
  _impl_.sender_pubkey_falcon_.ClearToEmpty();
  _impl_.metadata_.ClearToEmpty();
  _impl_.hash_.ClearToEmpty();
  _impl_.amount_str_.ClearToEmpty();
  ::memset(&_impl_.amount_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_system_) -
      reinterpret_cast<char*>(&_impl_.amount_)) + sizeof(_impl_.is_system_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TransactionProto::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TransactionProto& this_ = static_cast<const TransactionProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TransactionProto::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TransactionProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:alyncoin.TransactionProto)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string sender = 1;
          if (!this_._internal_sender().empty()) {
            const std::string& _s = this_._internal_sender();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "alyncoin.TransactionProto.sender");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string recipient = 2;
          if (!this_._internal_recipient().empty()) {
            const std::string& _s = this_._internal_recipient();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "alyncoin.TransactionProto.recipient");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // double amount = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_amount()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_amount(), target);
          }

          // uint64 timestamp = 4;
          if (this_._internal_timestamp() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_timestamp(), target);
          }

          // bytes signature_dilithium = 5;
          if (!this_._internal_signature_dilithium().empty()) {
            const std::string& _s = this_._internal_signature_dilithium();
            target = stream->WriteBytesMaybeAliased(5, _s, target);
          }

          // bytes signature_falcon = 6;
          if (!this_._internal_signature_falcon().empty()) {
            const std::string& _s = this_._internal_signature_falcon();
            target = stream->WriteBytesMaybeAliased(6, _s, target);
          }

          // bytes zkproof = 7;
          if (!this_._internal_zkproof().empty()) {
            const std::string& _s = this_._internal_zkproof();
            target = stream->WriteBytesMaybeAliased(7, _s, target);
          }

          // bytes sender_pubkey_dilithium = 8;
          if (!this_._internal_sender_pubkey_dilithium().empty()) {
            const std::string& _s = this_._internal_sender_pubkey_dilithium();
            target = stream->WriteBytesMaybeAliased(8, _s, target);
          }

          // bytes sender_pubkey_falcon = 9;
          if (!this_._internal_sender_pubkey_falcon().empty()) {
            const std::string& _s = this_._internal_sender_pubkey_falcon();
            target = stream->WriteBytesMaybeAliased(9, _s, target);
          }

          // string metadata = 10;
          if (!this_._internal_metadata().empty()) {
            const std::string& _s = this_._internal_metadata();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "alyncoin.TransactionProto.metadata");
            target = stream->WriteStringMaybeAliased(10, _s, target);
          }

          // string hash = 11;
          if (!this_._internal_hash().empty()) {
            const std::string& _s = this_._internal_hash();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "alyncoin.TransactionProto.hash");
            target = stream->WriteStringMaybeAliased(11, _s, target);
          }

          // bool is_system = 12;
          if (this_._internal_is_system() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                12, this_._internal_is_system(), target);
          }

          // string amount_str = 13;
          if (!this_._internal_amount_str().empty()) {
            const std::string& _s = this_._internal_amount_str();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "alyncoin.TransactionProto.amount_str");
            target = stream->WriteStringMaybeAliased(13, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:alyncoin.TransactionProto)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TransactionProto::ByteSizeLong(const MessageLite& base) {
          const TransactionProto& this_ = static_cast<const TransactionProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TransactionProto::ByteSizeLong() const {
          const TransactionProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:alyncoin.TransactionProto)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string sender = 1;
            if (!this_._internal_sender().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sender());
            }
            // string recipient = 2;
            if (!this_._internal_recipient().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_recipient());
            }
            // bytes signature_dilithium = 5;
            if (!this_._internal_signature_dilithium().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_signature_dilithium());
            }
            // bytes signature_falcon = 6;
            if (!this_._internal_signature_falcon().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_signature_falcon());
            }
            // bytes zkproof = 7;
            if (!this_._internal_zkproof().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_zkproof());
            }
            // bytes sender_pubkey_dilithium = 8;
            if (!this_._internal_sender_pubkey_dilithium().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_sender_pubkey_dilithium());
            }
            // bytes sender_pubkey_falcon = 9;
            if (!this_._internal_sender_pubkey_falcon().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_sender_pubkey_falcon());
            }
            // string metadata = 10;
            if (!this_._internal_metadata().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_metadata());
            }
            // string hash = 11;
            if (!this_._internal_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_hash());
            }
            // string amount_str = 13;
            if (!this_._internal_amount_str().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_amount_str());
            }
            // double amount = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_amount()) != 0) {
              total_size += 9;
            }
            // uint64 timestamp = 4;
            if (this_._internal_timestamp() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_timestamp());
            }
            // bool is_system = 12;
            if (this_._internal_is_system() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TransactionProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TransactionProto*>(&to_msg);
  auto& from = static_cast<const TransactionProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:alyncoin.TransactionProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sender().empty()) {
    _this->_internal_set_sender(from._internal_sender());
  }
  if (!from._internal_recipient().empty()) {
    _this->_internal_set_recipient(from._internal_recipient());
  }
  if (!from._internal_signature_dilithium().empty()) {
    _this->_internal_set_signature_dilithium(from._internal_signature_dilithium());
  }
  if (!from._internal_signature_falcon().empty()) {
    _this->_internal_set_signature_falcon(from._internal_signature_falcon());
  }
  if (!from._internal_zkproof().empty()) {
    _this->_internal_set_zkproof(from._internal_zkproof());
  }
  if (!from._internal_sender_pubkey_dilithium().empty()) {
    _this->_internal_set_sender_pubkey_dilithium(from._internal_sender_pubkey_dilithium());
  }
  if (!from._internal_sender_pubkey_falcon().empty()) {
    _this->_internal_set_sender_pubkey_falcon(from._internal_sender_pubkey_falcon());
  }
  if (!from._internal_metadata().empty()) {
    _this->_internal_set_metadata(from._internal_metadata());
  }
  if (!from._internal_hash().empty()) {
    _this->_internal_set_hash(from._internal_hash());
  }
  if (!from._internal_amount_str().empty()) {
    _this->_internal_set_amount_str(from._internal_amount_str());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_amount()) != 0) {
    _this->_impl_.amount_ = from._impl_.amount_;
  }
  if (from._internal_timestamp() != 0) {
    _this->_impl_.timestamp_ = from._impl_.timestamp_;
  }
  if (from._internal_is_system() != 0) {
    _this->_impl_.is_system_ = from._impl_.is_system_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TransactionProto::CopyFrom(const TransactionProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:alyncoin.TransactionProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TransactionProto::InternalSwap(TransactionProto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_, &other->_impl_.sender_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.recipient_, &other->_impl_.recipient_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_dilithium_, &other->_impl_.signature_dilithium_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_falcon_, &other->_impl_.signature_falcon_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.zkproof_, &other->_impl_.zkproof_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_pubkey_dilithium_, &other->_impl_.sender_pubkey_dilithium_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sender_pubkey_falcon_, &other->_impl_.sender_pubkey_falcon_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.metadata_, &other->_impl_.metadata_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hash_, &other->_impl_.hash_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.amount_str_, &other->_impl_.amount_str_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.is_system_)
      + sizeof(TransactionProto::_impl_.is_system_)
      - PROTOBUF_FIELD_OFFSET(TransactionProto, _impl_.amount_)>(
          reinterpret_cast<char*>(&_impl_.amount_),
          reinterpret_cast<char*>(&other->_impl_.amount_));
}

::google::protobuf::Metadata TransactionProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace alyncoin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_transaction_5fprotos_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
